Make write-commit-push job fail if it fixed files

diff --git a/src/orb.yml b/src/orb.yml
--- a/src/orb.yml
+++ b/src/orb.yml
@@ -81,6 +81,8 @@ commands:
             if [ -n "$(git status --porcelain)" ]; then
                 git commit --all --message "Format code with Prettier"
                 git push "$REMOTE_URL" "HEAD:${CIRCLE_BRANCH}"
+                # Indicate failure if we needed to fix formatting
+                exit 1
             else
                 echo "No changes to commit."
             fi
